import * as path from 'path';

const timestamp = Date.now().toString();

export const validBlogData = {
  numb: "0",
  slug: `blog-test-${timestamp}`,
  title: `Blog Automation ${timestamp}`,
  desc: `Đây là đoạn mô tả ngắn về blog được tự động tạo lúc ${timestamp}.`,
  content: `Đây là nội dung chi tiết của blog tự động tạo bởi Playwright lúc ${timestamp}.`,
  imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
  // Dữ liệu tiếng Anh (optional) - chỉ dùng khi web hỗ trợ 2 ngôn ngữ
  enData: {
    titleEn: `Automation Blog EN ${timestamp}`,
    slugEn: `automation-blog-en-${timestamp}`,
    descEn: `This is a short English description of the blog auto-generated at ${timestamp}.`,
    contentEn: `This is the detailed English content of the blog auto-generated by Playwright at ${timestamp}.`,
  }
};

export const invalidBlogCases = [
    {
        scenario: "không nhập tiêu đề",
        title: "",
        slug: `blog-${timestamp}`,
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    },
    {
        scenario: "không nhập đường dẫn mẫu",
        title: `Blog ${timestamp}`,
        slug: "",
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    }
];
