import * as path from 'path';

const timestamp = Date.now().toString();

export const validProjectData = {
  numb: "0",
  slug: `du-an-test-${timestamp}`,
  title: `Dự án Automation ${timestamp}`,
  desc: `Đây là đoạn mô tả ngắn về dự án được tự động tạo lúc ${timestamp}.`,
  content: `Đây là nội dung chi tiết của dự án tự động tạo bởi Playwright lúc ${timestamp}.`,
  imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
  // Dữ liệu tiếng Anh (optional) - chỉ dùng khi web hỗ trợ 2 ngôn ngữ
  enData: {
    titleEn: `Automation Project EN ${timestamp}`,
    slugEn: `automation-project-en-${timestamp}`,
    descEn: `This is a short English description of the project auto-generated at ${timestamp}.`,
    contentEn: `This is the detailed English content of the project auto-generated by Playwright at ${timestamp}.`,
  }
};

export const invalidProjectCases = [
    {
        scenario: "không nhập tiêu đề",
        title: "",
        slug: `du-an-${timestamp}`,
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    },
    {
        scenario: "không nhập đường dẫn mẫu",
        title: `Dự án ${timestamp}`,
        slug: "",
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    }
];
