import * as path from 'path';

const timestamp = Date.now().toString();

export const validRecruitmentData = {
  numb: "0",
  slug: `tuyen-dung-test-${timestamp}`,
  title: `Tuyển dụng Automation ${timestamp}`,
  desc: `Đây là đoạn mô tả ngắn về tuyển dụng được tự động tạo lúc ${timestamp}.`,
  content: `Đây là nội dung chi tiết của tin tuyển dụng tự động tạo bởi Playwright lúc ${timestamp}.`,
  imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
  // Dữ liệu tiếng Anh (optional) - chỉ dùng khi web hỗ trợ 2 ngôn ngữ
  enData: {
    titleEn: `Recruitment Automation EN ${timestamp}`,
    slugEn: `recruitment-automation-en-${timestamp}`,
    descEn: `This is a short English description of the recruitment auto-generated at ${timestamp}.`,
    contentEn: `This is the detailed English content of the recruitment auto-generated by Playwright at ${timestamp}.`,
  }
};

export const invalidRecruitmentCases = [
    {
        scenario: "không nhập tiêu đề",
        title: "",
        slug: `tuyen-dung-${timestamp}`,
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    },
    {
        scenario: "không nhập đường dẫn mẫu",
        title: `Tuyển dụng ${timestamp}`,
        slug: "",
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    }
];
