import * as path from 'path';

const timestamp = Date.now().toString();

export const validServiceData = {
  slug: `dich-vu-test-${timestamp}`,
  title: `Dịch vụ Automation ${timestamp}`,
  desc: `Đây là đoạn mô tả ngắn về dịch vụ được tự động tạo lúc ${timestamp}.`,
  content: `Đây là nội dung chi tiết của dịch vụ tự động tạo bởi Playwright lúc ${timestamp}.`,
  imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
  // Dữ liệu tiếng Anh (optional) - chỉ dùng khi web hỗ trợ 2 ngôn ngữ
  enData: {
    titleEn: `Automation Service EN ${timestamp}`,
    slugEn: `automation-service-en-${timestamp}`,
    descEn: `This is a short English description of the service auto-generated at ${timestamp}.`,
    contentEn: `This is the detailed English content of the service auto-generated by Playwright at ${timestamp}.`,
  }
};

export const invalidServiceCases = [
    {
        scenario: "không nhập tiêu đề",
        title: "",
        slug: `dich-vu-${timestamp}`,
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    },
    {
        scenario: "không nhập đường dẫn mẫu",
        title: `Dịch vụ ${timestamp}`,
        slug: "",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    }
];
