import * as path from 'path';

const timestamp = Date.now().toString();

export const validWarrantyData = {
  numb: "0",
  slug: `bao-hanh-sua-chua-test-${timestamp}`,
  title: `Bảo hành & sửa chữa Automation ${timestamp}`,
  desc: `Đây là đoạn mô tả ngắn về chính sách bảo hành & sửa chữa được tự động tạo lúc ${timestamp}.`,
  content: `Đây là nội dung chi tiết của chính sách bảo hành & sửa chữa tự động tạo bởi Playwright lúc ${timestamp}.`,
  imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
  // Dữ liệu tiếng Anh (optional) - chỉ dùng khi web hỗ trợ 2 ngôn ngữ
  enData: {
    titleEn: `Warranty & Repair Automation EN ${timestamp}`,
    slugEn: `warranty-repair-en-${timestamp}`,
    descEn: `This is a short English description of the warranty & repair policy auto-generated at ${timestamp}.`,
    contentEn: `This is the detailed English content of the warranty & repair policy auto-generated by Playwright at ${timestamp}.`,
  }
};

export const invalidWarrantyCases = [
    {
        scenario: "không nhập tiêu đề",
        title: "",
        slug: `bao-hanh-sua-chua-${timestamp}`,
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    },
    {
        scenario: "không nhập đường dẫn mẫu",
        title: `Bảo hành & sửa chữa ${timestamp}`,
        slug: "",
        numb: "0",
        desc: "Mô tả ngắn",
        content: "Nội dung",
        imagePath: path.resolve(process.cwd(), "data/images/test-image.jpg"),
        priority: "high",
        severity: "critical",
        assertionType: "form_block"
    }
];
